apiVersion: v1
kind: Service
metadata:
  name: bluemap-service
spec:
  selector:
    pod: bluemap
  ports:
    - protocol: HTTP
      port: 8100
      targetPort: 8100
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bluemap-route
spec:
  parentRefs:
  - name: cilium-gateway
    sectionName: bluemap-listener
  rules:
  - backendRefs:
    - name: bluemap-service
      port: 8100
