apiVersion: v1
kind: Service
metadata:
  name: bluemap-service
  labels:
    pod: bluemap
    service: bluemap-service
spec:
  selector:
    pod: bluemap
  ports:
    - port: 8100
      name: http
  externalTrafficPolicy: Local
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bluemap-route
spec:
  parentRefs:
  - name: cilium-gateway
    namespace: default
    sectionName: bluemap-listener
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: bluemap-service
        port: 8100
