apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-server-config
  labels:
    role: service-config
    pod: minecraft-server
data:
  EULA: "TRUE"
  TYPE: MODRINTH
  MODRINTH_LOADER: fabric
  MODRINTH_MODPACK: 1ocGzRHv
  MODRINTH_MODPACK_VERSION_TYPE: release
  MODRINTH_FORCE_SYNCHRONIZE: "TRUE"
  MODRINTH_EXCLUDE_FILES: |
    simple-datapacks
  VERSION: 1.21.11
  MEMORY: 6G
  DIFFICULTY: hard
  MOTD: "§l§c1.21.11 | McDaVanilla Perfected"
