apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  selector:
    pod: minecraft-server
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: minecraft-server-route
spec:
  parentRefs:
  - name: cilium-gateway
  rules:
  - backendRefs:
    - name: minecraft-service
      port: 25565
