apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 75Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minecraft/server"
