apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - name: minecraft-server-listener
    protocol: TCP
    port: 25565
    allowedRoutes:
      namespaces:
        from: All 
      kinds:
      - kind: TCPRoute
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-loadbalancer-pool"
spec:
  blocks:
    - start: "10.0.0.210"
      stop: "10.0.0.240"
