apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - name: bluemap-listener
    protocol: HTTP
    port: 8100
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-loadbalancer-pool"
spec:
  blocks:
    - start: "10.0.0.210"
      stop: "10.0.0.240"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: main-l2-policy
  namespace: kube-system
spec:
  externalIPs: true
  loadBalancerIPs: true
