apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - name: minecraft-server-listener
    protocol: TCP
    port: 25565
    allowedRoutes:
      kinds:
        - kind : TCPRoute
