---
- name: Install dnsmasq from package manager
  package:
    name: dnsmasq
    state: present

- name: Deploy dnsmasq.conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload dnsmasq
  systemd:
    name: dnsmasq
    state: reloaded
