apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: 10.0.0.131
      user: optiplex
      port: 22
      keyPath: /home/optiplex/.ssh/id_ed25519
    role: controller+worker
  - ssh:
      address: 10.0.0.148
      user: hp
      port: 22
      keyPath:  /home/optiplex/.ssh/id_ed25519
    role: worker
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
  k0s:
    config:
      spec:
        extensions:
          helm:
            repositories:
            - name: traefik
              url: https://helm.traefik.io/traefik
            - name: metallb
              url: https://metallb.github.io/metallb
            charts:
            - name: traefik
              chartname: traefik/traefik
              version: "38.0.2"
              namespace: default
            - name: metallb
              chartname: metallb/metallb
              version: "0.15.3"
              namespace: default
              values: |2
                configInline:
                  address-pools:
                  - name: generic-cluster-pool
                    protocol: layer2
                    addresses:
                    - 10.0.0.210-10.0.0.240
        network:
          provider: custom
          podCIDR: 172.20.0.0/16
          serviceCIDR: 172.21.0.0/16
