apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: 10.0.0.131
      user: optiplex
      port: 22
      keyPath: /home/optiplex/.ssh/id_ed25519
    role: controller+worker
    noTaints: true
  - ssh:
      address: 10.0.0.148
      user: hp
      port: 22
      keyPath:  /home/optiplex/.ssh/id_ed25519
    role: worker
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
  k0s:
    config:
      spec:
        network:
          provider: custom
          podCIDR: 172.20.0.0/16
          serviceCIDR: 172.21.0.0/16
          kubeproxy:
            disabled: true
